### ISSUE TITLE
功能需求，望采纳

### ISSUE THREAD

**Issue by Andowa** [znc15/Zibll-Newpostask#1]
请问能否实现和兑换码联动之类的，实现一个通过考试获得会员的功能？

**Comment by znc15** [comment]
就是考完试，然后给兑换码这样的吗

**Comment by Andowa** [comment]
> 就是考完试，然后给兑换码这样的吗

嗯，对。考完后，如果分数合格。可以生成一个永久会员的兑换码。（如果能实现无感激活的话就更好了，就是无需用户自己去激活，合格后，系统就自动激活会员了。）

**Comment by znc15** [comment]
好啦，终于有空弄一下
